import type {Catalog,State,Mobility,Ferry} from './types';
import {REGIONS,ferryNeedsReview,isStale,safeExternalUrl} from './domain.mjs';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(v:string|null|undefined)=>v?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Santiago'}).format(new Date(v)):'Sin consulta satisfactoria';
const link=(url:string,label:string)=>safeExternalUrl(url)?`<a class="text-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';
function ferryCard(f:Ferry,state:State){
 const review=ferryNeedsReview(f,state);
 return `<article class="ferry-card"><div class="eyebrow">CRUCE CON ${f.vehicles===true?'AUTO':f.vehicles===false?'PASAJEROS':'VEHÍCULO POR CONFIRMAR'}</div><h3>${esc(f.name)}</h3><p class="quiet">${esc(f.operator)} · ${esc(f.duration)}</p>${review?'<p class="review-needed">Horarios y condiciones por confirmar con el operador.</p>':''}<dl><dt>Reserva y embarque</dt><dd>${esc(f.bookingNote)}</dd><dt>Horarios publicados</dt><dd>${esc(f.schedule)}</dd><dt>Tarifa publicada</dt><dd>${esc(f.fare)}</dd></dl>${f.legs?`<ol class="ferry-legs">${f.legs.map(l=>`<li>${esc(l)}</li>`).join('')}</ol>`:''}<p class="quiet">Datos de la ficha consultados: ${date(f.observedAt)}${f.validUntil?` · Vigencia del itinerario: hasta ${date(f.validUntil)}`:''}. Confirmar fecha de viaje, sentido y categoría del vehículo.</p><div class="contact-actions">${link(f.booking,'Horarios, tarifas y reservas')}${f.terminals.map(t=>link(t.mapUrl,'Embarque: '+t.name)).join('')}</div><div class="ferry-sources">${f.sources.map(s=>{const o=state.observations[s.id];return `<p>${link(s.url,s.label)}<small>Última consulta: ${date(o?.checkedAt||s.checkedAt)}${o&&!o.ok?' · Consulta fallida':''}${o?.changed?' · La página cambió: revisión pendiente':''}${s.adapter==='reference'?' · Referencia de consulta manual':''}</small></p>`;}).join('')}</div></article>`;
}
export function renderMobility(catalog:Catalog,state:State,mobility:Mobility,region:string,route:string){
 const ferries=catalog.ferries.filter(f=>!route||f.routes.includes(route as 'main'|'austral'));
 const notices=mobility.notices.filter(n=>!region||n.region===region).sort((a,b)=>({closed:0,partial:1,unknown:2,open:3}[a.status]-{closed:0,partial:1,unknown:2,open:3}[b.status]));
 const stale=!mobility.ok||isStale(mobility.checkedAt);
 const labels={closed:'No operativo',partial:'Parcialmente operativo',unknown:'Estado por confirmar',open:'Operativo según aviso'};
 return `<div class="section-heading"><div><span class="eyebrow">ANTES DE SEGUIR</span><h2>Rutas y ferries.</h2></div><button id="mobility-refresh" class="secondary-button">↻ Actualizar información</button></div>${!navigator.onLine?'<p class="notice-banner">Sin conexión: fichas y avisos guardados. Consulta las fechas antes de usarlos.</p>':''}<p class="section-intro">Cruza con tu auto y consulta los avisos del camino. Estas fichas guardan la última información publicada; los cupos y zarpes se confirman con cada operador.</p><label class="mobility-select">Recorrido <select id="ferry-route"><option value="">Todos los cruces</option><option value="main" ${route==='main'?'selected':''}>Santiago–Quellón</option><option value="austral" ${route==='austral'?'selected':''}>Alternativa Austral</option></select></label><div class="ferry-grid">${ferries.map(f=>ferryCard(f,state)).join('')}</div><section class="road-section" aria-labelledby="road-title"><div class="section-heading"><div><span class="eyebrow">DIRECCIÓN DE VIALIDAD · MOP</span><h2 id="road-title">Avisos de caminos.</h2></div><label class="mobility-select">Región <select id="road-region"><option value="">Todas las regiones</option>${REGIONS.map(r=>`<option ${r===region?'selected':''}>${esc(r)}</option>`).join('')}</select></label></div><p class="notice-banner">${stale?'Revisión vial pendiente. ':''}${!mobility.ok?'La última consulta falló; se conserva la evidencia anterior. ':''}Última consulta satisfactoria: ${date(mobility.checkedAt)}. Que un camino no aparezca aquí no confirma que esté transitable.</p><p class="quiet">${link(mobility.sourceUrl,'Fuente oficial y alcance del servicio')} · Avisos en las regiones del viaje, no una evaluación de todo tu itinerario. Los puntos del MOP pueden representar tramos de forma aproximada.</p><p role="status">${notices.length} avisos${region?' en '+esc(region):''}</p><div class="road-list">${notices.length?notices.map(n=>`<article class="road-card"><div><span class="status ${stale?'unknown':n.status}"><i></i>${stale?'Estado por confirmar':labels[n.status]}</span><span class="quiet">${esc(n.region)}</span></div><h3>${esc(n.road||'Camino sin rol')} · ${esc(n.name)}</h3><p>${esc(n.summary)}</p>${n.restriction?`<p><strong>Restricción:</strong> ${esc(n.restriction)}</p>`:''}<p class="quiet">El aviso informa: ${esc(n.reportedStatus||'sin estado')}.</p><small>Evento: ${date(n.evidenceAt)} · Actualización en la fuente: ${date(n.updatedAt)}</small>${n.coordinates?`<p>${link('https://www.google.com/maps/search/?api=1&query='+n.coordinates.join(','),'Ubicación referencial del aviso')}</p>`:''}</article>`).join(''):'<p>No hay avisos en la última respuesta para esta selección. Consulta la fuente oficial antes de viajar.</p>'}</div></section>`;
}
